### ISSUE TITLE
getDataInBackgroundWithBlock not retrieving imageData due to ATS - swift2 xcode7.1

### ISSUE THREAD

**Issue by jeffvett** [ParsePlatform/Parse-SDK-iOS-OSX#349]
Hi, this array refuses to fill with the 7 images i've stored in my "Photos" table.  The only error I can find that might explain this is "App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file" 
I've tried both turning off ATS and adding the plist exceptions (pasted below), neither seems to work. 

var pageImages: [UIImage] = []

    func xyz() {

    let query = PFQuery(className:"Photos")

    query.whereKey("userId", equalTo: (PFUser.currentUser()!.objectId)!)

    query.findObjectsInBackgroundWithBlock({
        (objects: [AnyObject]?, error: NSError?) -> Void in

        if error == nil {

            for object in objects! {

                let userPicture = object["imageFile"] as! PFFile

                userPicture.getDataInBackgroundWithBlock { (imageData: NSData?, error: NSError?) -> Void in
                        if (error == nil) {
                            let image = UIImage(data:imageData!)
                            self.pageImages.append(image!)

                            print("pageImages.count \(self.pageImages.count)")

                        }
                    }
            }
            print("objects.count \(objects!.count)")
            print("pageImagesOutside.count \(self.pageImages.count)")    

        }
        self.loadPage()
    })
}

*****PList******

<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSExceptionDomains</key>
		<dict>
			<key>files.parsetfss.com</key>
			<dict>
				<key>NSIncludesSubdomains</key>
				<true/>
				<key>NSExceptionRquiresForwardSecrecy</key>
				<false/>
			</dict>
			<key>akamaihd.net</key>
			<dict>
				<key>NSExceptionRequiresForwardSecrecy</key>
				<false/>
				<key>NSIncludesSubdomains</key>
				<true/>
			</dict>
			<key>facebook.com</key>
			<dict>
				<key>NSExceptionRequiresForwardSecrecy</key>
				<false/>
				<key>NSIncludesSubdomains</key>
				<true/>
			</dict>
			<key>fbcdn.net</key>
			<dict>
				<key>NSExceptionRequiresForwardSecrecy</key>
				<false/>
				<key>NSIncludesSubdomains</key>
				<true/>
			</dict>
            <key>files.parse.com</key>
            <dict>
                <key>NSIncludesSubdomains</key>
                <true/>
                <key>NSExceptionAllowsInsecureHTTPLoads</key>
                <true/>
            </dict>
        </dict>
	</dict>

**Comment by richardjrossiii** [comment]
This should have been fixed since SDK version 1.8.3, which version are you using?

**Comment by jeffvett** [comment]
i have no idea what version.  I will update my frameworks.  

I was able to get around the problem by turning ATS off and updating xcode version to newest beta.  

thanks

**Comment by plaudev** [comment]
this issue persists even in 1.14.2. Turning ATS off is not an acceptable solution
