### ISSUE TITLE
Parse crash reporting doesn't work (both iOS and Android)

### ISSUE THREAD

**Issue by daniel-mihai** [ParsePlatform/Parse-SDK-iOS-OSX#444]
We are currently using parse for push notifications and analytics, and it works very well. Unfortunately, it doesn't work on crash reporting. On iOS we also did the upload of symbol files automatically. We also verified the troubleshooting section from ducumentation. It still doesn't send crashes. We are currently using XCode 6.4 to build the app, and the deployment target is 8.0. We added parse and parse crash reporting to our project using cocoapods. On Android the same problem, no crashes received.

**Comment by horseshoe7** [comment]
I have the same problem.  Followed all the instructions and it won't work.  Using Xcode 7, deployment target iOS 8.1

I found the documentation a bit lacking when setting this up.  For example the run script:

```
export PATH=/usr/local/bin:$PATH
cd <path_to_cloudcode_folder>

parse symbols <app_name_from_cloud_code_config_globals> --path="${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}"
```
where do I find ```<app_name_from_cloud_code_config_globals>```

**Comment by genius50** [comment]
Same for me, I'm using Parse Crash Reporting for Android with the last SDK version ! it seems to be a backend issue.

**Comment by daniel-mihai** [comment]
@horseshoe7 , it should be the app name you created or added to Cloud Code. View documentation here : https://parse.com/apps/quickstart#cloud_code/unix . So the run script looks like this 

export PATH=/usr/local/bin:$PATH
cd /Users/daniel/my_app_dir

parse symbols MyAppName --path="${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}"

And I have the "cloud" directory inside "my_app_dir"

It won't work anyway for this version of parse, so it's useless for now

**Comment by Nitewriter** [comment]
I'm also experiencing this issue. Triggered a couple dozen test crashes per the example yesterday. None of them are making it to the Parse admin portal.

**Comment by nlutsenko** [comment]
Hey guys, sorry for a late reply on this.
If you are still experiencing problems with this, here are the 2 steps I would recommend:
- Double check the console log after the crash happens when running in debug mode (please note the crash won't be captured if the debugger is attached).
- If there are no errors in the console log - it means that the crash reports where successfully sent to the server (you can also change the log level to `debug` by running `[Parse setLogLevel:PFLogLevelDebug];` (this will give more information about the count of crash reports uploaded)

If all above is still succeeding - then I believe the issue is purely in processing the crash reports, if that's the case - please file an issue via https://parse.com/help, as we are continuing to use FB Bug Tool to track backend issues.

**Comment by pronvit** [comment]
Any updates on this? I've integrated SDK and not getting test crash reports. When enabled logging, I see it's uploading reports on the next app launch but none of them appeared on the website.

**Comment by nlutsenko** [comment]
@pronvit As I specified previously - please file an issue via https://parse.com/help , since this looks to be a purely backend issue at this point, and it's not related to any client code.

**Comment by pronvit** [comment]
Well, there's just no category there to report crash reporting-related stuff. But ok, I'll report it in the Outages category.

**Comment by fsproru** [comment]
:+1: Submitted a related issue to FB Bug Tracking system https://developers.facebook.com/bugs/503791233122986/

**Comment by nlutsenko** [comment]
Hey guys, just wanted to update everyone here. 
This issue should be fixed as of yesterday. 
Sorry it took so long, but it was a really hard to track down cross data center issue on our backend.

I suggest you guys try it out and let me know how it goes.

**Comment by fsproru** [comment]
Thanks @nlutsenko. Let me try it out and I'll get back to you soon.

**Comment by fsproru** [comment]
@nlutsenko I just re-uploaded symbols and crash reports still show up as unsymbolicated
<img width="1038" alt="screen shot 2015-11-26 at 11 07 23 am" src="https://cloud.githubusercontent.com/assets/1017606/11430061/aa09696e-9435-11e5-802d-714669a84023.png">

Would you mind mind sharing this feedback with the back end team ?

**Comment by nlutsenko** [comment]
Certainly not.
If you have a bug open on FB Bug Tool - I would recommend pinging someone there as well.

On Nov 26, 2015, at 12:04 PM, Alex Tamoykin <notifications@github.com<mailto:notifications@github.com>> wrote:


@nlutsenko<https://github.com/nlutsenko> I just re-uploaded symbols and crash reports still show up as unsymbolicated
[screen shot 2015-11-26 at 11 07 23 am]<https://urldefense.proofpoint.com/v2/url?u=https-3A__cloud.githubusercontent.com_assets_1017606_11430061_aa09696e-2D9435-2D11e5-2D802d-2D714669a84023.png&d=CwMCaQ&c=5VD0RTtNlTh3ycd41b3MUw&r=_zSp4O6lfI-0uTcu2vf-uQ&m=aY_A-OfM-xFV8oXg5S0znaPyrhdPBoIgsh6RnxoAZeU&s=AqunocMjkv1CWLvDCsmG-lw7j8zUuDvV8bxSkRqwURI&e=>

Would you mind mind sharing this feedback with the back end team ?

**Comment by fsproru** [comment]
@nlutsenko, sounds like a plan.
