### ISSUE TITLE
Swift 2.2/XCode 7.3 compilation error: Incorrect argument label in call (have 'withoutDataWithObjectId:', expeced 'outDataWithObjectId:')

### ISSUE THREAD

**Issue by coolnalu** [ParsePlatform/Parse-SDK-iOS-OSX#864]
Ran into the problem after updating to XCode 7.3 this morning.

<img width="1109" alt="screen shot 2016-03-22 at 12 54 58 pm" src="https://cloud.githubusercontent.com/assets/319604/13960153/89691048-f02d-11e5-92c0-3870a2a613e2.png">

**Comment by nlutsenko** [comment]
@coolnalu, any chance you are using the latest SDK? This should be fixed as of 1.13.0 that was released yesterday.

**Comment by coolnalu** [comment]
@nlutsenko thanks for the quick reply. I did update to 1.13.0 today. and also deleted Parse from /Pods and reinstalled to prevent cached result. I saw your commit in #859 but still getting the error that's why I created the ticket.

**Comment by nlutsenko** [comment]
You also deleted `DerivedData`, I assume?

**Comment by coolnalu** [comment]
do you need to modify the method `+ (instancetype)objectWithoutDataWithObjectId:(nullable NSString *)objectId;` in PFObject+Subclass.h as well?

**Comment by coolnalu** [comment]
@nlutsenko just did and rebuilt. error didn't go away.

**Comment by nlutsenko** [comment]
(－‸ლ) I am looking at the wrong method, so sorry... Yup, that would be it.
I am not sure, but I believe SourceKit doesn't allow overriding constructors in protocols using `NS_SWIFT_NAME`, meaning that you would need to change the method.

**Comment by nlutsenko** [comment]
Going to try few more things here and get back to you.

**Comment by coolnalu** [comment]
@nlutsenko cool thanks!

**Comment by nlutsenko** [comment]
@coolnalu, in-place fix - change a line in Objective-C header that this is referencing (PFObject+Subclass.h) to 
```objc
+ (instancetype)objectWithoutDataWithObjectId:(nullable NSString *)objectId NS_SWIFT_NAME(init(withoutDataWithObjectId:));
```

Looks like it doesn't like it for whatever reason, so I am looking a solution that would be close, but the one that doesn't produce a warning.

**Comment by coolnalu** [comment]
@nlutsenko that fixed the compile. thanks!

**Comment by nlutsenko** [comment]
;) I breaks couple of our things, but I am trying to mitigate that...

**Comment by coolnalu** [comment]
:raised_hands: super. thanks!
