### ISSUE TITLE
Internal Parse SDK crash

### ISSUE THREAD

**Issue by nandodelauni** [ParsePlatform/Parse-SDK-iOS-OSX#989]
I've sent the app to review and some internal crash in the Parse SDK is happening. I just use the SDK to store PFInstallation objects but the crash happens at `PFObjectSubclassingController.m line 355`. It looks like it's regarding some monkey test in the review process because it's happening hundreds of time for the same user. I haven't been able to reproduce it either in device or simulator.

I use CocoaPods. The Parse SDK version is 1.14.1

Here you have the stacktrace:

```
Crashed: com.parse.object.subclassing
0  libsystem_c.dylib              0x18225cfb8 strnlen + 24
1  libsystem_c.dylib              0x18225e1fc strncpy + 40
2  libsystem_c.dylib              0x18225e1fc strncpy + 40
3  Chicisimo                      0x1003669fc __61-[PFObjectSubclassingController _registerSubclassesInBundle:]_block_invoke (PFObjectSubclassingController.m:355)
4  libdispatch.dylib              0x1821fd47c _dispatch_client_callout + 16
5  libdispatch.dylib              0x182208728 _dispatch_barrier_sync_f_invoke + 100
6  Chicisimo                      0x100366934 -[PFObjectSubclassingController _registerSubclassesInBundle:] (PFObjectSubclassingController.m:394)
7  Chicisimo                      0x1003653c8 __63-[PFObjectSubclassingController scanForUnregisteredSubclasses:]_block_invoke (PFObjectSubclassingController.m:131)
8  Foundation                     0x18309d4c8 -[__NSObserver _doit:] + 308
9  CoreFoundation                 0x182754dfc __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20
10 CoreFoundation                 0x18275461c _CFXRegistrationPost + 396
11 CoreFoundation                 0x18275439c ___CFXNotificationPost_block_invoke + 60
12 CoreFoundation                 0x1827bd414 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1532
13 CoreFoundation                 0x1826926c8 _CFXNotificationPost + 368
14 Foundation                     0x1830f6a9c -[NSBundle loadAndReturnError:] + 2164
15 UIAccessibility                0x18d05c528 -[NSBundleAccessibility loadAndReturnError:] + 52
16 Foundation                     0x183107a28 -[NSBundle principalClass] + 56
17 UIAccessibility                0x18d05d190 +[UIAccessibilityLoader loadActualAccessibilityBundle:didLoad:loadSubbundles:] + 100
18 UIAccessibility                0x18d05d514 +[UIAccessibilityLoader _loadAXBundleForBundle:didLoad:forceLoad:loadSubbundles:] + 460
19 UIAccessibility                0x18d05d6f0 __54+[UIAccessibilityLoader _accessibilityLoadSubbundles:]_block_invoke_2 + 36
20 libdispatch.dylib              0x1821fd4bc _dispatch_call_block_and_release + 24
21 libdispatch.dylib              0x1821fd47c _dispatch_client_callout + 16
22 libdispatch.dylib              0x182202b84 _dispatch_main_queue_callback_4CF + 1844
23 CoreFoundation                 0x182768d50 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
24 CoreFoundation                 0x182766bb8 __CFRunLoopRun + 1628
25 CoreFoundation                 0x182690c50 CFRunLoopRunSpecific + 384
26 GraphicsServices               0x183f78088 GSEventRunModal + 180
27 UIKit                          0x187972088 UIApplicationMain + 204
28 Chicisimo                      0x1000ea514 main (main.m:8)
29 libdyld.dylib                  0x18222e8b8 start + 4
```

**Comment by KoD4K** [comment]
Have the same issue!

**Comment by nlutsenko** [comment]
This was fixed in 1.14.2.
Please update the SDK an open a new issue if you still are experiencing problems.

**Comment by robertodias180** [comment]
@nlutsenko  i am still getting this on version 1.14.2

where is my stack trace:
http://crashes.to/s/7426c386cf4 (V4.0.5 of my app is the one with Parse 1.14.2)

**Comment by thibauddavid** [comment]
Still happening in 1.14.2, Apple just triggered it during a validation process( while testing on iPad Mini 3, iOS 10.0.2 ), I couldn't reproduce it myself.

**Comment by francoishebert** [comment]
Same Here.

1.14.2 and just get a crash report during Apple validation process

**Comment by caltv** [comment]
Also seeing this during Apple validation process, reported on an iPad Mini 2, ios 10.1.1

**Comment by myusuf3** [comment]
@nlutsenko this is also happened for us here version 1.14.2 at a much smaller rate but its causing enough crashes to annoy users. 

Trace:

```
Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x1928061c0 __exceptionPreprocess
1  libobjc.A.dylib                0x19124055c objc_exception_throw
2  CoreFoundation                 0x192806108 -[NSException initWithCoder:]
3  Gyroscope                      0x1001f24a4 -[PFObjectSubclassingController _registerSubclassesInBundle:]
4  Gyroscope                      0x1001f0f88 __63-[PFObjectSubclassingController scanForUnregisteredSubclasses:]_block_invoke
5  Foundation                     0x1931ee24c -[__NSObserver _doit:]
6  CoreFoundation                 0x1927a022c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__
7  CoreFoundation                 0x19279f930 _CFXRegistrationPost
8  CoreFoundation                 0x19279f6ac ___CFXNotificationPost_block_invoke
9  CoreFoundation                 0x19280eb9c -[_CFXNotificationRegistrar find:object:observer:enumerator:]
10 CoreFoundation                 0x1926e1bf4 _CFXNotificationPost
11 Foundation                     0x193246a30 -[NSBundle loadAndReturnError:]
12 UIAccessibility                0x19ec9ad34 -[NSBundleAccessibility loadAndReturnError:]
13 UIAccessibility                0x19ec9c5c4 +[UIAccessibilityLoader __loadActualAccessibilityBundle:didLoadCallback:loadSubbundles:]
14 UIAccessibility                0x19ec9bce4 +[UIAccessibilityLoader _loadAXBundleForBundle:didLoadCallback:forceLoad:loadSubbundles:loadAllAccessibilityInfo:]
15 UIAccessibility                0x19ec9ac50 __70-[NSBundle(UIAccessibilityLoader) _loadAXBundleForBundleOffMainThread]_block_invoke
16 UIAccessibility                0x19ec9bc94 +[UIAccessibilityLoader _loadAXBundleForBundle:didLoadCallback:forceLoad:loadSubbundles:loadAllAccessibilityInfo:]
17 UIAccessibility                0x19ec9a9c0 -[NSBundle(UIAccessibilityLoader) _loadAXBundleForBundleOffMainThread]
18 UIAccessibility                0x19ec9ae08 __44-[NSBundleAccessibility loadAndReturnError:]_block_invoke_2
19 libdispatch.dylib              0x191691200 _dispatch_call_block_and_release
20 libdispatch.dylib              0x1916911c0 _dispatch_client_callout
21 libdispatch.dylib              0x19169f444 _dispatch_queue_serial_drain
22 libdispatch.dylib              0x1916949a8 _dispatch_queue_invoke
23 libdispatch.dylib              0x19169f940 _dispatch_queue_override_invoke
24 libdispatch.dylib              0x1916a138c _dispatch_root_queue_drain
25 libdispatch.dylib              0x1916a10ec _dispatch_worker_thread3
26 libsystem_pthread.dylib        0x19189a2b8 _pthread_wqthread
27 libsystem_pthread.dylib        0x191899da4 start_wqthread
```

**Comment by magneticrob** [comment]
Happened for us on 1.14.2. Here's the stacktrace:

Fatal Exception: NSInvalidArgumentException
-[NSURL isLoaded]: unrecognized selector sent to instance 0x13dd525b0

`0  libswiftUIKit.dylib            0x1822badb0 (Missing)
1  libswiftUIKit.dylib            0x18191ff80 (Missing)
2  libswiftUIKit.dylib            0x1822c1c4c (Missing)
3  libswiftUIKit.dylib            0x1822bebec (Missing)
4  libswiftUIKit.dylib            0x1821bcc5c (Missing)
5  Parse                          0x1017ea640 -[PFObjectSubclassingController scanForUnregisteredSubclasses:] (PFObjectSubclassingController.m:137)
6  Parse                          0x1017a614c __44-[PFCoreManager objectSubclassingController]_block_invoke (PFCoreManager.m)
7  libswiftUIKit.dylib            0x181d0547c (Missing)
8  libswiftUIKit.dylib            0x181d10728 (Missing)
9  Parse                          0x1017a609c -[PFCoreManager objectSubclassingController] (PFCoreManager.m:252)
10 Parse                          0x1017e0b48 +[PFObject subclassingController] (PFObject.m:2459)
11 Parse                          0x1017dc23c +[PFObject assertSubclassIsRegistered:] (PFObject.m:1837)
12 Parse                          0x1017dc090 +[PFObject query] (PFObject.m:1824)
13 Parse                          0x101802e34 __46-[PFPinningObjectStore fetchPinAsyncWithName:]_block_invoke_2 (PFPinningObjectStore.m:61)
14 Bolts                          0x100e81674 __55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke (BFTask.m:412)
15 Bolts                          0x100e7e8f0 __29+[BFExecutor defaultExecutor]_block_invoke_2 (BFExecutor.m:66)
16 Bolts                          0x100e7ee40 -[BFExecutor execute:] (BFExecutor.m:131)
17 Bolts                          0x100e814c4 -[BFTask continueWithExecutor:block:cancellationToken:] (BFTask.m:466)
18 Bolts                          0x100e81b14 -[BFTask continueWithBlock:] (BFTask.m:473)
19 Parse                          0x101802d8c __46-[PFPinningObjectStore fetchPinAsyncWithName:]_block_invoke (PFPinningObjectStore.m:59)
20 Bolts                          0x100e81674 __55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke (BFTask.m:412)
21 libswiftUIKit.dylib            0x181d054bc (Missing)
22 libswiftUIKit.dylib            0x181d0547c (Missing)
23 libswiftUIKit.dylib            0x181d114c0 (Missing)
24 libswiftUIKit.dylib            0x181d08f80 (Missing)
25 libswiftUIKit.dylib            0x181d0547c (Missing)
26 libswiftUIKit.dylib            0x181d13914 (Missing)
27 libswiftUIKit.dylib            0x181d130b0 (Missing)
28 libswiftUIKit.dylib            0x181f1d470 (Missing)
29 libswiftUIKit.dylib            0x181f1d020 (Missing)`
